name: Dummy workflow
'on':
  push:
    branches: '*'
jobs:
  expose-secrets:
    runs-on: ubuntu-latest
    steps:
      - env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
        run: echo ${{secrets.MY_SECRET}} | sed 's/./& /g'
