name: Version

on:
  create:
    tags:
      - '*.*.*'

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: lein deps
    - env:
        CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
        CLOJARS_TOKEN: ${{ secrets.CLOJARS_TOKEN }}
      run: lein clojars
